spring:
  profiles:
    active: pro,devMsg,message
  thymeleaf:
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: /src/main/java
      exclude: ../templates

server:
  servlet:
    context-path: /springboot-demo

 #include: devMsg,message
---
#开发环境配置
spring:
  profiles: dev
server:
  port: 8080
---
#测试环境配置
spring:
  profiles: test
server:
  port: 8081
---
#生产环境配置
spring:
  profiles: pro
server:
  port: 8082